version: '3'

services:
  bierpass-api:
    container_name: bierpass-api
    image: bierpass-api:latest
    hostname: bierpass-api
    build:
      context: .
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      bierpass-database:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - bierpass-network
    
  bierpass-database:
    container_name: bierpass-database
    hostname: postgres
    image: postgres:latest
    ports:
      - 5433:5432
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bierpass-development
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bierpass-network

volumes:
  node_modules:
  database:

networks:
  bierpass-network:
    driver: bridge